ALTER TABLE MATEMBALAGEM
    ADD CONSTRAINT MATEMBALAGEM_MATUNIDADEMEDIDA_FK FOREIGN KEY(CD_UNIDADE_MEDIDA)
        REFERENCES MATUNIDADEMEDIDA(CD_UNIDADE_MEDIDA)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO