ALTER TABLE SEGUSUARIOPERFIL
    ADD CONSTRAINT SEGUSUARIOPERFIL_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO