ALTER TABLE ORCORCAMENTO
    ADD CONSTRAINT ORCORCAMENTO_CLBORGANIZACAO_FK FOREIGN KEY(CLBORGANIZACAO_CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO