ALTER TABLE ORCSEGMENTO
    ADD CONSTRAINT ORCSEGMENTO_CLBORGANIZACAO_FK FOREIGN KEY(CLBORGANIZACAO_CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO