ALTER TABLE ORCSEGMENTO
    ADD CONSTRAINT ORCSEGMENTO_ORCSEGMENTOPAI_FK FOREIGN KEY(ORCSEGMENTOPAI_CD_SEGMENTOPAI)
        REFERENCES ORCSEGMENTOPAI(CD_SEGMENTOPAI)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO