CREATE TABLE GEOCIDADE(
    CD_CIDADE      CF_CODIGO NOT NULL,
    DS_CIDADE      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    CD_UF          CF_CODIGO NOT NULL,
    CD_IBGE        CF_NUMERO_INTEIRO NULL
)

GO