CREATE TABLE GEOCONTINENTE(
    CD_CONTINENTE   CF_CODIGO NOT NULL,
    DS_CONTINENTE   CF_LITERAL_60 NOT NULL,
    DT_CADASTRO     CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO     CF_DATA_HORA NULL,
    DT_ALTERACAO    CF_DATA_HORA NOT NULL
)

GO