CREATE TABLE GEOENDERECO(
    CD_ENDERECO      CF_CODIGO NOT NULL,
    DS_ENDERECO      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO      CF_DATA_HORA NOT NULL,
    DT_ALTERACAO     CF_DATA_HORA NULL,
    DT_EXCLUSAO      CF_DATA_HORA NULL,
    DS_LOGRADOURO    CF_LITERAL_60 NULL,
    DS_NUMERO        CF_LITERAL_60 NULL,
    DS_COMPLEMENTO   CF_LITERAL_60 NULL,
    DS_BAIRRO        CF_LITERAL_60 NULL,
    NR_CEP           CF_NUMERO_INTEIRO NULL,
    CD_PESSOA        CF_CODIGO NOT NULL
)

GO