CREATE TABLE GEOUF(
    CD_UF          CF_CODIGO NOT NULL,
    DS_UF          CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    CD_PAIS        CF_CODIGO NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DS_SIGLA       CF_LITERAL_2 NULL
)

GO