ALTER TABLE GEOUF ADD CONSTRAINT GEOUF_PK PRIMARY KEY CLUSTERED (CD_UF ASC)
     
GO
ALTER TABLE GEOUF ADD CONSTRAINT GEOUF_CD_PAIS_CD_UF_DS_SIGLA_UN UNIQUE NONCLUSTERED(CD_PAIS ASC,CD_UF ASC,DS_SIGLA ASC)
GO