CREATE TABLE ITTPESSOA(
    CD_PESSOA            CF_CODIGO NOT NULL,
    DS_NOME_PESSOA       CF_LITERAL_60 NOT NULL,
    DT_CADASTRO          CF_DATA_HORA NOT NULL,
    DT_ALTERACAO         CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO          CF_DATA_HORA NULL,
    NR_CNPJ              CF_CNPJ NULL,
    NR_CPF               CF_CPF NULL,
    NR_IESTADUAL         CF_IESTADUAL NULL,
    NR_IMUNICIPAL        CF_LITERAL_15 NULL,
    NR_IESTRANGEIRO      CF_LITERAL_20 NULL,
    NR_ISUFRAMA          CF_NUMERO_INTEIRO NULL,
    NR_IEXPORTADOR       CF_LITERAL_60 NULL,
    NR_IFABRICANTE       CF_LITERAL_60 NULL,
    "DS_NOME-FANTASIA"   CF_LITERAL_60 NULL
)

GO