CREATE TABLE SEGUSUARIO(
    CD_USUARIO             CF_CODIGO NOT NULL,
    DS_NOME_USUARIO        CF_LITERAL_60 NOT NULL,
    DT_CADASTRO            CF_DATA_HORA NOT NULL,
    DT_ALTERACAO           CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO            CF_DATA_HORA NULL,
    DS_EMAIL               CF_LITERAL_256 NOT NULL,
    DT_CONFIRMACAO_EMAIL   CF_DATA_HORA NULL
)

GO