-- Gerado por Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   em:        2019-01-19 11:50:09 BRST
--   site:      SQL Server 2012
--   tipo:      SQL Server 2012



CREATE TABLE CLBORGANIZACAO(
    CD_ORGANIZACAO   CF_CODIGO NOT NULL,
    DS_ORGANIZACAO   CF_LITERAL_20 NOT NULL,
    DT_CADASTRO      CF_DATA_HORA NOT NULL,
    DT_ALTERACAO     CF_DATA_HORA NULL,
    DT_EXCLUSAO      CF_DATA_HORA NULL
)

GO

ALTER TABLE CLBORGANIZACAO ADD CONSTRAINT CLBORGANIZACAO_PK PRIMARY KEY CLUSTERED(CD_ORGANIZACAO ASC)

GO

CREATE TABLE CLBUSUARIO_ORGANIZ(
    CD_USUARIO_ORGANIZ   CF_CODIGO NOT NULL,
    CD_USUARIO           CF_CODIGO NOT NULL,
    CD_ORGANIZACAO       CF_CODIGO NOT NULL,
    ID_ADMIN             CF_BOLEANO NOT NULL
)

GO

ALTER TABLE CLBUSUARIO_ORGANIZ ADD CONSTRAINT CLBUSUARIO_ORGANIZ_PK PRIMARY KEY CLUSTERED(CD_USUARIO_ORGANIZ ASC)

GO

CREATE TABLE COMCONDICAO(
    CD_CONDICAO        CF_CODIGO NOT NULL,
    DS_CONDICAO        CF_LITERAL_60 NOT NULL,
    DT_CADASTRO        CF_DATA_HORA NOT NULL,
    DT_ALTERACAO       CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO        CF_DATA_HORA NULL,
    NR_IND_PAGAMENTO   CF_NUMERO_INTEIRO NULL
)

GO

ALTER TABLE COMCONDICAO ADD CONSTRAINT COMCONDICAO_PK PRIMARY KEY CLUSTERED(CD_CONDICAO ASC)

GO

CREATE TABLE COMOPERACAO(
    CD_OPERACAO      CF_CODIGO NOT NULL,
    DS_OPERACAO      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO      CF_DATA_HORA NOT NULL,
    DT_ALTERACAO     CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO      CF_DATA_HORA NULL,
    NR_ID_SENTIDO    CF_NUMERO_INTEIRO NOT NULL,
    NR_ID_PRESENCA   CF_NUMERO_INTEIRO NOT NULL
)

GO

ALTER TABLE COMOPERACAO ADD CONSTRAINT COMOPERACAO_PK PRIMARY KEY CLUSTERED(CD_OPERACAO ASC)

GO

CREATE TABLE COMPEDIDO(
    CD_PEDIDO      CF_CODIGO NOT NULL,
    DS_PEDIDO      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL
)

GO

ALTER TABLE COMPEDIDO ADD CONSTRAINT COMPEDIDO_PK PRIMARY KEY CLUSTERED(CD_PEDIDO ASC)

GO

CREATE TABLE COMPEDIDOITEM(
    CD_ITEM        CF_CODIGO NOT NULL,
    DS_ITEM        CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    CD_EMBALADO    CF_CODIGO NOT NULL,
    CD_PEDIDO      CF_CODIGO NOT NULL
)

GO

ALTER TABLE COMPEDIDOITEM ADD CONSTRAINT COMPEDIDOITEM_PK PRIMARY KEY CLUSTERED(CD_ITEM ASC)

GO

CREATE TABLE COMPRECO(
    CD_PRECO                 CF_NUMERO_INTEIRO NOT NULL,
    DS_PRECO                 CF_LITERAL_60 NOT NULL,
    DT_CADASTRO              CF_DATA_HORA NOT NULL,
    DT_ALTERACAO             CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO              CF_DATA_HORA NULL,
    DT_VIGENCIA_INICIO       CF_DATA_HORA NOT NULL,
    DT_VIGENCIA_FINAL        CF_DATA_HORA NULL,
    DT_VIGENCIA_PRORROGADA   CF_DATA_HORA NULL
)

GO

ALTER TABLE COMPRECO ADD CONSTRAINT COMPRECO_PK PRIMARY KEY CLUSTERED(CD_PRECO ASC)

GO

CREATE TABLE COMPRECOITEM(
    CD_ITEM        CF_NUMERO_INTEIRO NOT NULL,
    DS_ITEM        CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    CD_PRECO       CF_NUMERO_INTEIRO NOT NULL,
    CD_EMBALADO    CF_CODIGO NOT NULL,
    VL_UNITARIO    CF_NUMERO_DECIMAL NOT NULL
)

GO

ALTER TABLE COMPRECOITEM ADD CONSTRAINT COMPRECOITEM_PK PRIMARY KEY CLUSTERED(CD_ITEM ASC)

GO

CREATE TABLE DEPOBJETO(
    CD_OBJETO         CF_CODIGO NOT NULL,
    DS_OBJETO         CF_LITERAL_60 NULL,
    DT_CADASTRO       CF_DATA_HORA NOT NULL,
    DT_ALTERACAO      CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO       CF_DATA_HORA NULL,
    BL_OBJETO         CF_BINARIO NOT NULL,
    DS_CAMINHO        CF_LITERAL_60 NULL,
    DS_ARQUIVO        CF_LITERAL_60 NULL,
    DS_ARQUIVO_TIPO   CF_LITERAL_15 NULL
)

GO

ALTER TABLE DEPOBJETO ADD CONSTRAINT DEPOBJETO_PK PRIMARY KEY CLUSTERED(CD_OBJETO ASC GO 

CREATE TABLE GEOCIDADE(
    CD_CIDADE      CF_CODIGO NOT NULL,
    DS_CIDADE      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    CD_UF          CF_CODIGO NOT NULL,
    CD_IBGE        CF_NUMERO_INTEIRO NULL
)

GO

ALTER TABLE GEOCIDADE ADD CONSTRAINT GEOCIDADE_PK PRIMARY KEY CLUSTERED(CD_CIDADE ASC GO 

CREATE TABLE GEOCONTINENTE(
    CD_CONTINENTE   CF_CODIGO NOT NULL,
    DS_CONTINENTE   CF_LITERAL_60 NOT NULL,
    DT_CADASTRO     CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO     CF_DATA_HORA NULL,
    DT_ALTERACAO    CF_DATA_HORA NOT NULL
)

GO

ALTER TABLE GEOCONTINENTE ADD CONSTRAINT GEOCONTINENTE_PK PRIMARY KEY CLUSTERED(CD_CONTINENTE ASC)

GO

CREATE TABLE GEOENDERECO(
    CD_ENDERECO      CF_CODIGO NOT NULL,
    DS_ENDERECO      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO      CF_DATA_HORA NOT NULL,
    DT_ALTERACAO     CF_DATA_HORA NULL,
    DT_EXCLUSAO      CF_DATA_HORA NULL,
    DS_LOGRADOURO    CF_LITERAL_60 NULL,
    DS_NUMERO        CF_LITERAL_60 NULL,
    DS_COMPLEMENTO   CF_LITERAL_60 NULL,
    DS_BAIRRO        CF_LITERAL_60 NULL,
    NR_CEP           CF_NUMERO_INTEIRO NULL,
    CD_PESSOA        CF_CODIGO NOT NULL
)

GO

ALTER TABLE GEOENDERECO ADD CONSTRAINT GEOENDERECO_PK PRIMARY KEY CLUSTERED(CD_ENDERECO ASC GO 

CREATE TABLE GEOPAIS(
    CD_PAIS         CF_CODIGO NOT NULL,
    DS_PAIS         CF_LITERAL_60 NOT NULL,
    DT_CADASTRO     CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO     CF_DATA_HORA NULL,
    CD_CONTINENTE   CF_CODIGO NOT NULL,
    DT_ALTERACAO    CF_DATA_HORA NOT NULL,
    CD_IBGE         CF_NUMERO_INTEIRO NULL
)

GO

ALTER TABLE GEOPAIS ADD CONSTRAINT GEOPAIS_PK PRIMARY KEY CLUSTERED(CD_PAIS ASC GO 

CREATE TABLE GEOUF(
    CD_UF          CF_CODIGO NOT NULL,
    DS_UF          CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    CD_PAIS        CF_CODIGO NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DS_SIGLA       CF_LITERAL_2 NULL
)

GO

ALTER TABLE GEOUF ADD CONSTRAINT GEOUF_PK PRIMARY KEY CLUSTERED (CD_UF ASC)
     
GO
ALTER TABLE GEOUF ADD CONSTRAINT GEOUF_CD_PAIS_CD_UF_DS_SIGLA_UN UNIQUE NONCLUSTERED(CD_PAIS ASC,CD_UF ASC,DS_SIGLA ASC)
GO

CREATE TABLE ITTPESSOA(
    CD_PESSOA         CF_CODIGO NOT NULL,
    DS_NOME_PESSOA    CF_LITERAL_60 NOT NULL,
    DT_CADASTRO       CF_DATA_HORA NOT NULL,
    DT_ALTERACAO      CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO       CF_DATA_HORA NULL,
    NR_CNPJ           CF_CNPJ NULL,
    NR_CPF            CF_CPF NULL,
    NR_IESTADUAL      CF_IESTADUAL NULL,
    NR_IMUNICIPAL     CF_LITERAL_15 NULL,
    NR_IESTRANGEIRO   CF_LITERAL_20 NULL,
    NR_ISUFRAMA       CF_NUMERO_INTEIRO NULL,
    NR_IEXPORTADOR    CF_LITERAL_60 NULL,
    NR_IFABRICANTE    CF_LITERAL_60 NULL
)

GO

ALTER TABLE ITTPESSOA ADD CONSTRAINT ITTPESSOA_PK PRIMARY KEY CLUSTERED(CD_PESSOA ASC GO 

CREATE TABLE MATCLASSE(
    CD_CLASSE      CF_CODIGO NOT NULL,
    DS_CLASSE      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL
)

GO

ALTER TABLE MATCLASSE ADD CONSTRAINT MATCLASSE_PK PRIMARY KEY CLUSTERED(CD_CLASSE ASC GO 

CREATE TABLE MATEMBALADO(
    CD_EMBALADO    CF_CODIGO NOT NULL,
    DS_EMBALADO    CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    CD_EMBALAGEM   CF_CODIGO NOT NULL,
    CD_PRODUTO     CF_CODIGO NOT NULL
)

GO

ALTER TABLE MATEMBALADO ADD CONSTRAINT MATEMBALADO_PK PRIMARY KEY CLUSTERED(CD_EMBALADO ASC GO 

CREATE TABLE MATEMBALAGEM(
    CD_EMBALAGEM        CF_CODIGO NOT NULL,
    DS_EMBALAGEM        CF_LITERAL_60 NOT NULL,
    DT_CADASTRO         CF_DATA_HORA NOT NULL,
    DT_ALTERACAO        CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO         CF_DATA_HORA NULL,
    NR_PESO             CF_NUMERO_DECIMAL NULL,
    NR_CAPACIDADE       CF_NUMERO_DECIMAL NULL,
    CD_UNIDADE_MEDIDA   CF_CODIGO NOT NULL
)

GO

ALTER TABLE MATEMBALAGEM ADD CONSTRAINT MATEMBALAGEM_PK PRIMARY KEY CLUSTERED(CD_EMBALAGEM ASC GO 

CREATE TABLE MATESTOQUE(
    CD_ESTOQUE             CF_CODIGO NOT NULL,
    DS_ESTOQUE             CF_LITERAL_60 NOT NULL,
    DT_CADASTRO            CF_DATA_HORA NOT NULL,
    DT_ALTERACAO           CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO            CF_DATA_HORA NULL,
    NR_QUANTIDADE          CF_NUMERO_DECIMAL NULL,
    NR_QUANTIDADE_MINIMA   CF_NUMERO_DECIMAL NULL,
    NR_QUANTIDADE_PEDIDO   CF_NUMERO_DECIMAL NULL,
    NR_QUANTIDADE_MAXIMA   CF_NUMERO_DECIMAL NULL,
    CD_LOCAL               CF_CODIGO NOT NULL,
    CD_EMBALADO            CF_CODIGO NOT NULL
)

GO

ALTER TABLE MATESTOQUE ADD CONSTRAINT MATESTOQUE_PK PRIMARY KEY CLUSTERED(CD_ESTOQUE ASC GO 

CREATE TABLE MATLOCAL(
    CD_LOCAL       CF_CODIGO NOT NULL,
    DS_LOCAL       CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL
)

GO

ALTER TABLE MATLOCAL ADD CONSTRAINT MATLOCAL_PK PRIMARY KEY CLUSTERED(CD_LOCAL ASC GO 

CREATE TABLE MATPRODUTO(
    CD_PRODUTO     CF_CODIGO NOT NULL,
    DS_PRODUTO     CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL,
    CD_CLASSE      CF_CODIGO NOT NULL
)

GO

ALTER TABLE MATPRODUTO ADD CONSTRAINT MATPRODUTO_PK PRIMARY KEY CLUSTERED(CD_PRODUTO ASC GO 

CREATE TABLE MATUNIDADEMEDIDA(
    CD_UNIDADE_MEDIDA   CF_CODIGO NOT NULL,
    DS_UNIDADE_MEDIDA   CF_LITERAL_60 NOT NULL,
    DT_CADASTRO         CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO         CF_DATA_HORA NULL,
    DT_ALTERACAO        CF_DATA_HORA NOT NULL,
    DS_SIGLA            CF_LITERAL_60 NOT NULL
)

GO

ALTER TABLE MATUNIDADEMEDIDA ADD CONSTRAINT MATUNIDADEMEDIDA_PK PRIMARY KEY CLUSTERED(CD_UNIDADE_MEDIDA ASC GO 

CREATE TABLE ORCORCAMENTO(
    CD_ORCAMENTO                    CF_CODIGO NOT NULL,
    DS_ORCAMENTO                    CF_LITERAL_60 NOT NULL,
    DT_CADASTRO                     CF_DATA_HORA NOT NULL,
    DT_ALTERACAO                    CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO                     CF_DATA_HORA NULL,
    CLBORGANIZACAO_CD_ORGANIZACAO   CF_CODIGO NOT NULL,
    DT_INICIAL                      CF_DATA_HORA NOT NULL,
    DT_FINAL                        CF_DATA_HORA NOT NULL,
    VL_ORCAMENTO                    CF_NUMERO_DECIMAL NOT NULL
)

GO

ALTER TABLE ORCORCAMENTO ADD CONSTRAINT ORCORCAMENTO_PK PRIMARY KEY CLUSTERED(CD_ORCAMENTO ASC GO 

CREATE TABLE ORCORCAMENTOMESANO(
    CD_ORCAMENTOMESANO          CF_CODIGO NOT NULL,
    DS_ORCAMENTOMESANO          CF_LITERAL_60 NULL,
    DT_CADASTRO                 CF_DATA_HORA NOT NULL,
    DT_ALTERACAO                CF_DATA_HORA NOT NULL,
    DT_MES_ANO                  CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO                 CF_DATA_HORA NULL,
    VL_PLANEJADO                CF_NUMERO_DECIMAL NULL,
    VL_COMPRAS                  CF_NUMERO_DECIMAL NOT NULL,
    VL_SALDO                    CF_NUMERO_DECIMAL NULL,
    VL_ATRIBUIDO                CF_NUMERO_DECIMAL NULL,
    ORCORCAMENTO_CD_ORCAMENTO   CF_CODIGO NOT NULL
)

GO

ALTER TABLE ORCORCAMENTOMESANO ADD CONSTRAINT ORCORCAMENTOMESANO_PK PRIMARY KEY CLUSTERED(CD_ORCAMENTOMESANO ASC GO 

CREATE TABLE ORCSEGMENTO(
    CD_SEGMENTO                     CF_CODIGO NOT NULL,
    DS_SEGMENTO                     CF_LITERAL_60 NOT NULL,
    DT_CADASTRO                     CF_DATA_HORA NOT NULL,
    DT_ALTERACAO                    CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO                     CF_DATA_HORA NULL,
    CLBORGANIZACAO_CD_ORGANIZACAO   CF_CODIGO NOT NULL,
    VL_PLANEJADO                    CF_NUMERO_DECIMAL NOT NULL,
    VL_COMPRAS                      CF_NUMERO_DECIMAL NOT NULL,
    VL_SALDO                        CF_NUMERO_DECIMAL NOT NULL,
    VL_ATRIBUIDO                    CF_NUMERO_DECIMAL NOT NULL,
    ORCSEGMENTOPAI_CD_SEGMENTOPAI   CF_CODIGO NULL
)

GO

ALTER TABLE ORCSEGMENTO ADD CONSTRAINT ORCSEGMENTO_PK PRIMARY KEY CLUSTERED(CD_SEGMENTO ASC GO 

CREATE TABLE ORCSEGMENTOPAI(
    CD_SEGMENTOPAI   CF_CODIGO NOT NULL,
    DS_SEGMENTOPAI   CF_LITERAL_60 NOT NULL,
    DT_CADASTRO      CF_DATA_HORA NOT NULL,
    DT_ALTERACAO     CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO      CF_DATA_HORA NULL,
    CD_ORGANIZACAO   CF_CODIGO NOT NULL,
    VL_PLANEJADO     CF_NUMERO_DECIMAL NOT NULL,
    VL_COMPRAS       CF_NUMERO_DECIMAL NOT NULL,
    VL_SALDO         CF_NUMERO_DECIMAL NOT NULL,
    VL_ATRIBUIDO     CF_NUMERO_DECIMAL NOT NULL
)

GO

ALTER TABLE ORCSEGMENTOPAI ADD CONSTRAINT ORCSEGMENTOPAI_PK PRIMARY KEY CLUSTERED(CD_SEGMENTOPAI ASC GO 

CREATE TABLE SEGOBJETO(
    CD_OBJETO      CF_CODIGO NOT NULL,
    DS_OBJETO      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL
)

GO

ALTER TABLE SEGOBJETO ADD CONSTRAINT SEGOBJETO_PK PRIMARY KEY CLUSTERED(CD_OBJETO ASC GO 

CREATE TABLE SEGPANDORA(
    CD_PANDORA              CF_CODIGO NOT NULL,
    DS_PANDORA              CF_LITERAL_256 NULL,
    DT_CADASTRO             CF_DATA_HORA NOT NULL,
    DT_ALTERACAO            CF_DATA_HORA NULL,
    DT_EXCLUSAO             CF_DATA_HORA NULL,
    SEGUSUARIO_CD_USUARIO   CF_CODIGO NOT NULL
)

GO

ALTER TABLE SEGPANDORA ADD CONSTRAINT SEGPANDORA_PK PRIMARY KEY CLUSTERED(CD_PANDORA ASC GO 

CREATE TABLE SEGPERFIL(
    CD_PERFIL      CF_CODIGO NOT NULL,
    DS_PERFIL      CF_LITERAL_60 NULL,
    DT_CADASTRO    CF_DATA_HORA NOT NULL,
    DT_ALTERACAO   CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO    CF_DATA_HORA NULL
)

GO

ALTER TABLE SEGPERFIL ADD CONSTRAINT SEGPERFIL_PK PRIMARY KEY CLUSTERED(CD_PERFIL ASC GO 

CREATE TABLE SEGPERMISSAO(
    CD_PERMISSAO          CF_CODIGO NOT NULL,
    DS_PERMISSAO          CF_LITERAL_60 NULL,
    DT_CADASTRO           CF_DATA_HORA NOT NULL,
    DT_ALTERACAO          CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO           CF_DATA_HORA NULL,
    SEGPERFIL_CD_PERFIL   CF_CODIGO NOT NULL,
    SEGOBJETO_CD_OBJETO   CF_CODIGO NOT NULL
)

GO

CREATE TABLE SEGTOKEN(
    CD_TOKEN                CF_CODIGO NOT NULL,
    DS_TOKEN                CF_LITERAL_256 NOT NULL,
    DS_IP_CLIENTE           CF_LITERAL_20 NOT NULL,
    DT_CADASTRO             CF_DATA_HORA NOT NULL,
    DT_ALTERACAO            CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO             CF_DATA_HORA NULL,
    SEGUSUARIO_CD_USUARIO   CF_CODIGO NOT NULL
)

GO

ALTER TABLE SEGTOKEN ADD CONSTRAINT SEGTOKEN_PK PRIMARY KEY CLUSTERED(CD_TOKEN ASC GO 

CREATE TABLE SEGUSUARIO(
    CD_USUARIO             CF_CODIGO NOT NULL,
    DS_NOME_USUARIO        CF_LITERAL_60 NOT NULL,
    DT_CADASTRO            CF_DATA_HORA NOT NULL,
    DT_ALTERACAO           CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO            CF_DATA_HORA NULL,
    DS_EMAIL               CF_LITERAL_256 NOT NULL,
    DT_CONFIRMACAO_EMAIL   CF_DATA_HORA NULL
)

GO

ALTER TABLE SEGUSUARIO ADD CONSTRAINT SEGUSUARIO_PK PRIMARY KEY CLUSTERED (CD_USUARIO ASC)
     
GO
ALTER TABLE SEGUSUARIO ADD CONSTRAINT SEGUSUARIO_DS_EMAIL_UN UNIQUE NONCLUSTERED(DS_EMAIL ASC GO 

CREATE TABLE SEGUSUARIOPERFIL(
    CD_ITEM                 CF_CODIGO NOT NULL,
    DS_ITEM                 CF_LITERAL_60 NOT NULL,
    DT_CADASTRO             CF_DATA_HORA NOT NULL,
    DT_ALTERACAO            CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO             CF_DATA_HORA NULL,
    SEGUSUARIO_CD_USUARIO   CF_CODIGO NOT NULL,
    SEGPERFIL_CD_PERFIL     CF_CODIGO NOT NULL
)

GO

ALTER TABLE SEGUSUARIOPERFIL ADD CONSTRAINT SEGUSUARIOPERFIL_PK PRIMARY KEY CLUSTERED(CD_ITEM ASC,DT_CADASTRO ASC)
     
GO

CREATE TABLE SEGUSUARIOPESSOA(
    CD_USUARIOPESSOA      CF_CODIGO NOT NULL,
    DS_USUARIOPESSOA      CF_LITERAL_60 NOT NULL,
    DT_CADASTRO           CF_DATA_HORA NOT NULL,
    DT_ALTERACAO          CF_DATA_HORA NOT NULL,
    DT_EXCLUSAO           CF_DATA_HORA NULL,
    ITTPESSOA_CD_PESSOA   CF_CODIGO NOT NULL
)

GO

ALTER TABLE SEGUSUARIOPESSOA ADD CONSTRAINT SEGUSUARIOPESSOA_PK PRIMARY KEY CLUSTERED(CD_USUARIOPESSOA ASC GO 

CREATE TABLE SEGUSUARIOQ(
    CD_USUARIOQ             CF_CODIGO NOT NULL,
    DS_PERGUNTA             CF_LITERAL_256 NOT NULL,
    DS_RESPOSTA             CF_LITERAL_256 NOT NULL,
    DT_CADASTRO             CF_DATA_HORA NOT NULL,
    DT_ALTERACAO            CF_DATA_HORA NULL,
    DT_EXCLUSAO             CF_DATA_HORA NULL,
    SEGUSUARIO_CD_USUARIO   CF_CODIGO NOT NULL
)

GO

ALTER TABLE CLBUSUARIO_ORGANIZ
    ADD CONSTRAINT CLBUSUARIO_ORGANIZ_CLBORGANIZACAO_FK FOREIGN KEY(CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE CLBUSUARIO_ORGANIZ
    ADD CONSTRAINT CLBUSUARIO_ORGANIZ_SEGUSUARIO_FK FOREIGN KEY(CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPEDIDOITEM
    ADD CONSTRAINT COMPEDIDOITEM_COMPEDIDO_FK FOREIGN KEY(CD_PEDIDO)
        REFERENCES COMPEDIDO(CD_PEDIDO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPEDIDOITEM
    ADD CONSTRAINT COMPEDIDOITEM_MATEMBALADO_FK FOREIGN KEY(CD_EMBALADO)
        REFERENCES MATEMBALADO(CD_EMBALADO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPRECOITEM
    ADD CONSTRAINT COMPRECOITEM_COMPRECO_FK FOREIGN KEY(CD_PRECO)
        REFERENCES COMPRECO(CD_PRECO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPRECOITEM
    ADD CONSTRAINT COMPRECOITEM_MATEMBALADO_FK FOREIGN KEY(CD_EMBALADO)
        REFERENCES MATEMBALADO(CD_EMBALADO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOCIDADE
    ADD CONSTRAINT GEOCIDADE_GEOUF_FK FOREIGN KEY(CD_UF)
        REFERENCES GEOUF(CD_UF)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOENDERECO
    ADD CONSTRAINT GEOENDERECO_ITTPESSOA_FK FOREIGN KEY(CD_PESSOA)
        REFERENCES ITTPESSOA(CD_PESSOA)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOPAIS
    ADD CONSTRAINT GEOPAIS_GEOCONTINENTE_FK FOREIGN KEY(CD_CONTINENTE)
        REFERENCES GEOCONTINENTE(CD_CONTINENTE)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOUF
    ADD CONSTRAINT GEOUF_GEOPAIS_FK FOREIGN KEY(CD_PAIS)
        REFERENCES GEOPAIS(CD_PAIS)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATEMBALADO
    ADD CONSTRAINT MATEMBALADO_MATEMBALAGEM_FK FOREIGN KEY(CD_EMBALAGEM)
        REFERENCES MATEMBALAGEM(CD_EMBALAGEM)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATEMBALADO
    ADD CONSTRAINT MATEMBALADO_MATPRODUTO_FK FOREIGN KEY(CD_PRODUTO)
        REFERENCES MATPRODUTO(CD_PRODUTO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATEMBALAGEM
    ADD CONSTRAINT MATEMBALAGEM_MATUNIDADEMEDIDA_FK FOREIGN KEY(CD_UNIDADE_MEDIDA)
        REFERENCES MATUNIDADEMEDIDA(CD_UNIDADE_MEDIDA)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATESTOQUE
    ADD CONSTRAINT MATESTOQUE_MATEMBALADO_FK FOREIGN KEY(CD_EMBALADO)
        REFERENCES MATEMBALADO(CD_EMBALADO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATESTOQUE
    ADD CONSTRAINT MATESTOQUE_MATLOCAL_FK FOREIGN KEY(CD_LOCAL)
        REFERENCES MATLOCAL(CD_LOCAL)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATPRODUTO
    ADD CONSTRAINT MATPRODUTO_MATCLASSE_FK FOREIGN KEY(CD_CLASSE)
        REFERENCES MATCLASSE(CD_CLASSE)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCORCAMENTO
    ADD CONSTRAINT ORCORCAMENTO_CLBORGANIZACAO_FK FOREIGN KEY(CLBORGANIZACAO_CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCORCAMENTOMESANO
    ADD CONSTRAINT ORCORCAMENTOMESANO_ORCORCAMENTO_FK FOREIGN KEY(ORCORCAMENTO_CD_ORCAMENTO)
        REFERENCES ORCORCAMENTO(CD_ORCAMENTO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCSEGMENTO
    ADD CONSTRAINT ORCSEGMENTO_CLBORGANIZACAO_FK FOREIGN KEY(CLBORGANIZACAO_CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCSEGMENTO
    ADD CONSTRAINT ORCSEGMENTO_ORCSEGMENTOPAI_FK FOREIGN KEY(ORCSEGMENTOPAI_CD_SEGMENTOPAI)
        REFERENCES ORCSEGMENTOPAI(CD_SEGMENTOPAI)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGPANDORA
    ADD CONSTRAINT SEGPANDORA_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGPERMISSAO
    ADD CONSTRAINT SEGPERMISSAO_SEGOBJETO_FK FOREIGN KEY(SEGOBJETO_CD_OBJETO)
        REFERENCES SEGOBJETO(CD_OBJETO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGPERMISSAO
    ADD CONSTRAINT SEGPERMISSAO_SEGPERFIL_FK FOREIGN KEY(SEGPERFIL_CD_PERFIL)
        REFERENCES SEGPERFIL(CD_PERFIL)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGTOKEN
    ADD CONSTRAINT SEGTOKEN_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOPERFIL
    ADD CONSTRAINT SEGUSUARIOPERFIL_SEGPERFIL_FK FOREIGN KEY(SEGPERFIL_CD_PERFIL)
        REFERENCES SEGPERFIL(CD_PERFIL)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOPERFIL
    ADD CONSTRAINT SEGUSUARIOPERFIL_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOPESSOA
    ADD CONSTRAINT SEGUSUARIOPESSOA_ITTPESSOA_FK FOREIGN KEY(ITTPESSOA_CD_PESSOA)
        REFERENCES ITTPESSOA(CD_PESSOA)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOQ
    ADD CONSTRAINT SEGUSUARIOQ_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE CLBUSUARIO_ORGANIZ
    ADD CONSTRAINT CLBUSUARIO_ORGANIZ_CLBORGANIZACAO_FK FOREIGN KEY(CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE CLBUSUARIO_ORGANIZ
    ADD CONSTRAINT CLBUSUARIO_ORGANIZ_SEGUSUARIO_FK FOREIGN KEY(CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPEDIDOITEM
    ADD CONSTRAINT COMPEDIDOITEM_COMPEDIDO_FK FOREIGN KEY(CD_PEDIDO)
        REFERENCES COMPEDIDO(CD_PEDIDO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPEDIDOITEM
    ADD CONSTRAINT COMPEDIDOITEM_MATEMBALADO_FK FOREIGN KEY(CD_EMBALADO)
        REFERENCES MATEMBALADO(CD_EMBALADO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPRECOITEM
    ADD CONSTRAINT COMPRECOITEM_COMPRECO_FK FOREIGN KEY(CD_PRECO)
        REFERENCES COMPRECO(CD_PRECO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE COMPRECOITEM
    ADD CONSTRAINT COMPRECOITEM_MATEMBALADO_FK FOREIGN KEY(CD_EMBALADO)
        REFERENCES MATEMBALADO(CD_EMBALADO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOCIDADE
    ADD CONSTRAINT GEOCIDADE_GEOUF_FK FOREIGN KEY(CD_UF)
        REFERENCES GEOUF(CD_UF)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOENDERECO
    ADD CONSTRAINT GEOENDERECO_ITTPESSOA_FK FOREIGN KEY(CD_PESSOA)
        REFERENCES ITTPESSOA(CD_PESSOA)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOPAIS
    ADD CONSTRAINT GEOPAIS_GEOCONTINENTE_FK FOREIGN KEY(CD_CONTINENTE)
        REFERENCES GEOCONTINENTE(CD_CONTINENTE)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE GEOUF
    ADD CONSTRAINT GEOUF_GEOPAIS_FK FOREIGN KEY(CD_PAIS)
        REFERENCES GEOPAIS(CD_PAIS)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATEMBALADO
    ADD CONSTRAINT MATEMBALADO_MATEMBALAGEM_FK FOREIGN KEY(CD_EMBALAGEM)
        REFERENCES MATEMBALAGEM(CD_EMBALAGEM)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATEMBALADO
    ADD CONSTRAINT MATEMBALADO_MATPRODUTO_FK FOREIGN KEY(CD_PRODUTO)
        REFERENCES MATPRODUTO(CD_PRODUTO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATEMBALAGEM
    ADD CONSTRAINT MATEMBALAGEM_MATUNIDADEMEDIDA_FK FOREIGN KEY(CD_UNIDADE_MEDIDA)
        REFERENCES MATUNIDADEMEDIDA(CD_UNIDADE_MEDIDA)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATESTOQUE
    ADD CONSTRAINT MATESTOQUE_MATEMBALADO_FK FOREIGN KEY(CD_EMBALADO)
        REFERENCES MATEMBALADO(CD_EMBALADO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATESTOQUE
    ADD CONSTRAINT MATESTOQUE_MATLOCAL_FK FOREIGN KEY(CD_LOCAL)
        REFERENCES MATLOCAL(CD_LOCAL)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE MATPRODUTO
    ADD CONSTRAINT MATPRODUTO_MATCLASSE_FK FOREIGN KEY(CD_CLASSE)
        REFERENCES MATCLASSE(CD_CLASSE)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCORCAMENTO
    ADD CONSTRAINT ORCORCAMENTO_CLBORGANIZACAO_FK FOREIGN KEY(CLBORGANIZACAO_CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCORCAMENTOMESANO
    ADD CONSTRAINT ORCORCAMENTOMESANO_ORCORCAMENTO_FK FOREIGN KEY(ORCORCAMENTO_CD_ORCAMENTO)
        REFERENCES ORCORCAMENTO(CD_ORCAMENTO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCSEGMENTO
    ADD CONSTRAINT ORCSEGMENTO_CLBORGANIZACAO_FK FOREIGN KEY(CLBORGANIZACAO_CD_ORGANIZACAO)
        REFERENCES CLBORGANIZACAO(CD_ORGANIZACAO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE ORCSEGMENTO
    ADD CONSTRAINT ORCSEGMENTO_ORCSEGMENTOPAI_FK FOREIGN KEY(ORCSEGMENTOPAI_CD_SEGMENTOPAI)
        REFERENCES ORCSEGMENTOPAI(CD_SEGMENTOPAI)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGPANDORA
    ADD CONSTRAINT SEGPANDORA_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGPERMISSAO
    ADD CONSTRAINT SEGPERMISSAO_SEGOBJETO_FK FOREIGN KEY(SEGOBJETO_CD_OBJETO)
        REFERENCES SEGOBJETO(CD_OBJETO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGPERMISSAO
    ADD CONSTRAINT SEGPERMISSAO_SEGPERFIL_FK FOREIGN KEY(SEGPERFIL_CD_PERFIL)
        REFERENCES SEGPERFIL(CD_PERFIL)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGTOKEN
    ADD CONSTRAINT SEGTOKEN_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOPERFIL
    ADD CONSTRAINT SEGUSUARIOPERFIL_SEGPERFIL_FK FOREIGN KEY(SEGPERFIL_CD_PERFIL)
        REFERENCES SEGPERFIL(CD_PERFIL)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOPERFIL
    ADD CONSTRAINT SEGUSUARIOPERFIL_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOPESSOA
    ADD CONSTRAINT SEGUSUARIOPESSOA_ITTPESSOA_FK FOREIGN KEY(ITTPESSOA_CD_PESSOA)
        REFERENCES ITTPESSOA(CD_PESSOA)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO

ALTER TABLE SEGUSUARIOQ
    ADD CONSTRAINT SEGUSUARIOQ_SEGUSUARIO_FK FOREIGN KEY(SEGUSUARIO_CD_USUARIO)
        REFERENCES SEGUSUARIO(CD_USUARIO)
ON DELETE NO ACTION 
    ON UPDATE NO ACTION GO



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            35
-- CREATE INDEX                             0
-- ALTER TABLE                             91
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
